theme: jekyll-theme-cayman
markdown: kramdown

title: Vivek Chavan
description: PhD researcher in Industrial AI, Egocentric Vision, and Robotics

nav_links:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "Resources"
    url: "/resources/"
  - title: "Projects"
    url: "/projects/"
  - title: "Openings"
    url: "/openings/"
  - title: "Social"
    url: "/social/"
  - title: "Contact"
    url: "/contact/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:title/
future: true

/* --- Navbar mobile fix --- */
nav {
  line-height: 1.8; /* increase spacing between stacked links */
  padding-top: 0.8em;
  padding-bottom: 0.8em;
}

/* Ensure the header expands properly on smaller screens */
@media (max-width: 768px) {
  header {
    padding-top: 1em;
    padding-bottom: 1em;
  }

  nav {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 0.6em;
  }
}
