theme: jekyll-theme-cayman
markdown: kramdown

title: Vivek Chavan
description: PhD researcher in Industrial AI, Egocentric Vision, and Robotics

nav_links:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "Resources"
    url: "/resources/"
  - title: "Social"
    url: "/social/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:title/
future: true
